// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace CineworldPortable.Entities
{
    internal class DatesResponse
    {
        [JsonProperty("dates")]
        public string[] Dates { get; set; }
    }
}
