// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace CineworldPortable.Entities
{
    public class Event
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    internal class EventsResponse
    {
        [JsonProperty("events")]
        public Event[] Events { get; set; }
    }

}
