// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace CineworldPortable.Entities
{
    internal class PerformancesResponse
    {
        [JsonProperty("performances")]
        public Performance[] Performances { get; set; }
    }

}
